"""Dropped registered_crops column in users table and instead created a new table name usercrops

Revision ID: 91093cc40d5e
Revises: ef7d84dba67e
Create Date: 2025-02-25 17:42:58.806100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91093cc40d5e'
down_revision = 'ef7d84dba67e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_crops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('crop_name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_crops')
    # ### end Alembic commands ###
