"""Added column category in user_crops

Revision ID: d049bf06c982
Revises: 91093cc40d5e
Create Date: 2025-02-25 18:05:48.591984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd049bf06c982'
down_revision = '91093cc40d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_crops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_crops', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
